services:
  bnos:
    build: logs/.
    container_name: bnos
    image: suchcodewow/bnos-orderservice

  bnosbiz:
    build: bizevents/.
    container_name: bnosbiz
    image: suchcodewow/bnos-orderservicebiz
